### ISSUE TITLE
返回的数据和直接搜索的数据不一致。

### ISSUE THREAD

**Issue by tianci** [GraySilver/wencai#2]
```
strategy = wc.get_strategy("上升通道")
print(strategy)
```
返回
```
 日期    股票代码  股票简称   涨跌幅  当日收盘价(元)  dde大单净量（%）  股本规模   换手率
0  2018-11-06  000002   万科A -2.36     24.04       -0.10  超大盘股  0.60
1  2018-11-06  000008  神州高铁  3.43      4.52       -0.04   中盘股  2.03
```

和问财主页上返回的[结果](http://x.10jqka.com.cn/stockpick/search?typed=1&preParams=&ts=1&f=1&qs=result_rewrite&selfsectsn=&querytype=stock&searchfilter=&tid=stockpick&w=2018-11-06%20%E4%B8%8A%E5%8D%87%E9%80%9A%E9%81%93&queryarea=)不一致

**Comment by GraySilver** [comment]
已更新，欢迎使用～
