### ISSUE TITLE
测试有问题

### ISSUE THREAD

**Issue by henshan2002** [GraySilver/wencai#5]
![图片](https://user-images.githubusercontent.com/23010531/67178237-7ca8e200-f404-11e9-95f5-bbfd0989bb91.png)
请看图

**Comment by GraySilver** [comment]
没安装selenium这个包，试试pip install selenium==3.141

**Comment by henshan2002** [comment]
安装好selenium包后，运行又有错误。


  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/.goldminer3/projects/e557dbd9-e743-11e9-acce-00ff1c4aa94a/main.py", line 7, in <module>
    benchmark='hs000300')

TypeError: get_strategy() got an unexpected keyword argument 'benchmark'

**Comment by GraySilver** [comment]
Md还没完全更新，已更新示例。

**Comment by henshan2002** [comment]
我呢是非常想要你这个包，但是测试多次，都无法运行。
错误如下：
AttributeError: 'NoneType' object has no attribute 'quit'

**Comment by GraySilver** [comment]
你可能没安装好chrome和chromedriver，版本更新后已经有邮件反馈可用，如果你用不了以后麻烦截下图给你的运行环境。
