### ISSUE TITLE
# wc.get_strategy(策略回测) 运行结果不显示 #历史明细

### ISSUE THREAD

**Issue by huyangnl** [GraySilver/wencai#8]
print(r.profit_data) # 累计收益数据
print(r.backtest_data) # 报告评级
print(r.condition_data) # 准确回测语句
**print(r.history_detail(period='2')) # 历史明细查询**
print(r.history_pick(trade_date='2020-11-19', hold_num=1)) # 策略选股

history_detail 这一句输出的dataframe为空是怎么回事？

Empty DataFrame
Columns: []
Index: []

**Comment by huyangnl** [comment]
已解决：
修改 cons.py 中的：

WENCAI_CRAWLER_URL 部分， 找到：
`'history_detail': 'http://backtest.10jqka.com.cn/backtestonce/historydetail?\`
改为：

`'history_detail': 'http://backtest.10jqka.com.cn/tradebacktest/historydetail?\

**Comment by GraySilver** [comment]
thx，会在下一版本更新
